# NumPy
NumPy(Numerical Python) is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures.

## Key Features of NumPy
- **N-Dimensional Array Object**: NumPy introduces the ndarray, a powerful n-dimensional array object of same data type that allows for efficient storage and manipulation of large datasets.
    - **Performance**: NumPy is implemented in C and Fortran, which makes it much faster than traditional Python lists for numerical computations.
    - **Vectorized Operations**: NumPy allows for vectorized operations, enabling element-wise operations on arrays without the need for explicit loops.Like SIMD (Single Instruction, Multiple Data) operations, this leads to more concise and readable code.
    - **Memory Efficiency**: NumPy arrays consume less memory compared to Python lists, making them more efficient for large datasets. In Python lists, each element is a separate object, whereas in NumPy arrays, elements are stored in a contiguous block of memory.
    - **Array Indexing and Slicing**: NumPy provides advanced indexing and slicing capabilities, allowing users to access and manipulate subsets of data easily.
    - **Data Types**: NumPy supports a wide range of data types, including integers, floats, complex numbers, and more, allowing for precise control over memory usage and computational performance.
- **Broadcasting**: NumPy supports broadcasting, which allows for arithmetic operations on arrays of different shapes.
- **Mathematical Functions**: NumPy provides a wide range of mathematical functions, including trigonometric, statistical, and algebraic functions.
- **Linear Algebra**: NumPy includes functions for performing linear algebra operations, such as matrix multiplication, eigenvalue decomposition, and singular value decomposition.
- **Random Number Generation**: NumPy has a built-in module for generating random numbers, which is useful for simulations and probabilistic modeling.
- **Integration with Other Libraries**: NumPy is often used in conjunction with other scientific computing libraries, such as SciPy, Pandas, and Matplotlib.


## N-Dimensional Array Object

In [41]:
import numpy as np

## 1-Dimensional Array Object
a = np.array([1, 2, 3, 4, 5])
print("type:", type(a))

# 2-Dimensional Array Object
b = np.array([[1, 2, 3], # first row
              [4, 5, 6]]) # second row

# 3-Dimensional Array Object
# It's like a cube or a stack of matrices. Pile of 2D arrays.
c = np.array([[[1, 2, 3],    # first matrix, first row
               [4, 5, 6]],   # first matrix, second row
              [[7, 8, 9],    # second matrix, first row
               [10, 11, 12]]])# second matrix, second row

type: <class 'numpy.ndarray'>


In [42]:
# Array Attributes

print("Number of dimensions:", a.ndim, b.ndim, c.ndim)  # number of dimensions
print("Shape of the array:", a.shape, b.shape, c.shape) # shape of the array, means no. of rows and columns
print("Size of the array:", a.size, b.size, c.size)    # total number of elements
print("Data type of the array:", a.dtype, b.dtype, c.dtype) # data type of the elements

Number of dimensions: 1 2 3
Shape of the array: (5,) (2, 3) (2, 2, 3)
Size of the array: 5 6 12
Data type of the array: int64 int64 int64


In [43]:
# Data Types

# NumPy get the data type of the array elements by default while creating an array by upcasting. It supports various data types like:
# int8, int16, int32, int64, uint8, uint16, uint32, uint64, u32, float16, float32, float64, complex64, complex128, bool, object, string_, unicode_ etc.

# But we can also specify the data type explicitly while creating an array using the dtype parameter or astype() method.
d = np.array([1, 2, 3, 4], dtype=np.float64) # specifying data type as float64
print(d.dtype)
d = d.astype(np.int32) # converting data type to int32
print(d.dtype)

e=np.array([1,True, "Hello", 3.5])
print("Type for mixed array:",e.dtype)

float64
int32
Type for mixed array: <U32


In [44]:
# n-D arrays creation from existing data

# From a list or tuple
list_1d = [1, 2, 3, 4, 5]
array_from_list = np.array(list_1d)

tuple_2d = ((1, 2, 3), (4, 5, 6))
array_from_tuple = np.array(tuple_2d)

print("Array from list:", array_from_list)
print("Array from tuple:\n", array_from_tuple)

# From a set
set_1d = {1, 2, 3, 4, 5}
array_from_set_1d = np.array(list(set_1d), dtype=int)
print("Array from 1d set:", array_from_set_1d)

set_2d = { (1, 2, 3), (4, 5, 6) }
array_from_set_2d = np.array(list(set_2d))
array_from_set_2d = array_from_set_2d.astype(int)
print("Array from 2d set:\n", array_from_set_2d)

# From a dictionary
dict_data = {'a': 1, 'b': 2, 'c': 3}
array_from_dict_keys = np.array(list(dict_data.keys()))
array_from_dict_values = np.array(list(dict_data.values()))
array_from_dict_items = np.array(list(dict_data.items()))
print("Array from dict keys:", array_from_dict_keys)
print("Array from dict values:", array_from_dict_values)
print("Array from dict items:\n", array_from_dict_items)

Array from list: [1 2 3 4 5]
Array from tuple:
 [[1 2 3]
 [4 5 6]]
Array from 1d set: [1 2 3 4 5]
Array from 2d set:
 [[1 2 3]
 [4 5 6]]
Array from dict keys: ['a' 'b' 'c']
Array from dict values: [1 2 3]
Array from dict items:
 [['a' '1']
 ['b' '2']
 ['c' '3']]


In [45]:
# Creating n-D array from scratch

zeros_array = np.zeros((2, 3)) # 2 rows, 3 columns, filled with zeros
zeros_like_array= np.zeros_like(array_from_tuple) # array with same shape as array_from_tuple, filled with zeros
ones_array = np.ones((3, 2))   # 3 rows, 2 columns, filled with ones
ones_like_array = np.ones_like(array_from_tuple) # array with same shape as ones_array, filled with ones

empty_array = np.empty((2, 2),dtype=np.int32) # 2 rows, 2 columns, uninitialized values from junk memory
full_array = np.full((2, 3), 7) # 2 rows, 3 columns, filled with 7
full_infinity_array = np.full((2, 3), np.inf) # 2 rows, 3 columns, filled with infinity
full_like_array = np.full_like(array_from_tuple, 9) # array with same shape as array_from_tuple, filled with 9

identity_matrix = np.eye(3)    # 3x3 identity matrix

print("Zeros Array:\n", zeros_array)
print("Zeros Like Array:\n", zeros_like_array)
print("Ones Array:\n", ones_array)
print("Ones Like Array:\n", ones_like_array)

print("Empty Array:\n", empty_array)
print("Full Array:\n", full_array)
print("Full Infinity Array:\n", full_infinity_array)
print("Full Like Array:\n", full_like_array)

print("Identity Matrix:\n", identity_matrix)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Zeros Like Array:
 [[0 0 0]
 [0 0 0]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Ones Like Array:
 [[1 1 1]
 [1 1 1]]
Empty Array:
 [[        0         0]
 [727857104       385]]
Full Array:
 [[7 7 7]
 [7 7 7]]
Full Infinity Array:
 [[inf inf inf]
 [inf inf inf]]
Full Like Array:
 [[9 9 9]
 [9 9 9]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
# Creating n-D with random values
random_array = np.random.rand(2, 3)        # 2 rows, 3 columns, random values between 0 and 1
random_integer_array = np.random.randint(0, 10, (3, 4)) # 3 rows, 4 columns, random integers between 0 and 9 (start , end-1, shape)
random_uniform_array = np.random.uniform(1.0, 5.0, (2, 2)) # 2 rows, 2 columns, random float values between 1.0 and 5.0


print("Random Array:\n", random_array)
print("Random Integer Array:\n", random_integer_array)
print("Random Uniform Array:\n", random_uniform_array)

Random Array:
 [[0.56704811 0.17680863 0.04112348]
 [0.35384491 0.39450415 0.36613234]]
Random Integer Array:
 [[0 4 6 1]
 [3 7 6 8]
 [4 1 9 8]]
Random Uniform Array:
 [[2.44165144 1.6196021 ]
 [1.8365753  2.50944764]]
